Update BroodkeeperDiurna.lua
BigWigsMods/BigWigs pull request #1300
Opened 2022-12-15 17:20 UTC by ej22

Added functionality to mark Drakanid Stormbringer with a Diamond. Useful for heroic/mythic due to needing to interrupt static jolt and being able to auto mark this NPC will allow raiders to easier set up MRT notes for interrupt rotations.

2022-12-15 17:29 UTC, Justw8 requested changes
Please address the comments!

2022-12-15 17:29 UTC, Justw8 commented on VaultOfTheIncarnates/BroodkeeperDiurna.lua
> +		self:RegisterTargetEvents("AddMarking2")
Registering this if you also have primalistMageMarker enabled will overwrite the :RegisterTargetEvents, only 1 can be active. Thus you have to merge the 2 into 1 AddMarking function.

2022-12-15 17:29 UTC, Justw8 commented on VaultOfTheIncarnates/BroodkeeperDiurna.lua
> +function mod:AddMarking2(_, unit, guid)
See above comment, this needs to be merged with AddMarking so they can work along eachother.

2022-12-15 17:29 UTC, Justw8 commented on VaultOfTheIncarnates/BroodkeeperDiurna.lua
> +	self:Death("stormbringerDeath", 191232) -- Drakonid Stormbringer
We use Pascal Case for these functions, please capitalize the S.

2022-12-15 17:29 UTC, Justw8 commented on VaultOfTheIncarnates/BroodkeeperDiurna.lua
> +function mod:stormbringerDeath(args)
We use Pascal Case for these functions, please capitalize the S.

2022-12-15 18:10 UTC, ej22 commented
changes made as best as I can, only new to LUA so not sure if done correctly

2022-12-16 14:06 UTC, Justw8 commented
Almost there, requesting a few more fixes :)

2022-12-16 14:08 UTC, Justw8 requested changes

2022-12-16 14:08 UTC, Justw8 commented on VaultOfTheIncarnates/BroodkeeperDiurna.lua
>  	if self:GetOption(primalistMageMarker) then
merge the two if statements `if X or Y then`

2022-12-16 14:08 UTC, Justw8 commented on VaultOfTheIncarnates/BroodkeeperDiurna.lua
> +		else if guid and not mobCollector[guid] and self:MobId(guid) == 191232 then -- Drakonid Stormbringer
The checks are good, but the tabs are 1 off, also 1 extra end I think because of it. Please correct!

2022-12-16 18:53 UTC, ej22 commented
Changes implemented hopefully correctly. Thank you for your patience with this

2022-12-16 19:15 UTC, Justw8 requested changes

2022-12-16 19:15 UTC, Justw8 commented on VaultOfTheIncarnates/BroodkeeperDiurna.lua
> +	if self:GetOption(primalistMageMarker or stormbringerMarker) then
```suggestion
	if self:GetOption(primalistMageMarker) or self:GetOption(stormbringerMarker ) then
```

2022-12-16 19:15 UTC, Justw8 commented on VaultOfTheIncarnates/BroodkeeperDiurna.lua
>  	end
```suggestion
	elseif guid and not mobCollector[guid] and self:MobId(guid) == 191232 then -- Drakonid Stormbringer
		for i = 3, -1 do -- 3
			if not stormbringerMarks[i] then
				mobCollector[guid] = true
				stormbringerMarks[i] = guid
				self:CustomIcon(stormbringerMarker, unit, i)
				return
			end
		end
	end
```

2022-12-16 19:15 UTC, Justw8 commented
See above, that is how I meant them :)

2022-12-16 20:07 UTC, ej22 commented
Should be all fixed now <3

2022-12-18 20:10 UTC, closed without merging